import { PrismaClient } from '../src/generated/prisma/client'
import { PrismaPg } from '@prisma/adapter-pg'

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! })
const prisma = new PrismaClient({ adapter })

const alumnos = [
  {
    apellidoNombre: 'García López, Juan',
    tipoDocumento: 'DNI' as const,
    numeroDocumento: '35000123',
    fechaNacimiento: new Date('1998-03-15'),
    email: 'juan.garcia@example.com',
    telefono: '3815550101',
    legajo: '1001',
    plan: 'Contador Público',
    anoIngreso: 2020,
    fechaIngreso: new Date('2020-03-01'),
    estadoInscripcion: 'Regular',
    paisOrigen: 'Argentina',
  },
  {
    apellidoNombre: 'Martínez Ruiz, María',
    tipoDocumento: 'DNI' as const,
    numeroDocumento: '36000234',
    fechaNacimiento: new Date('1999-07-22'),
    email: 'maria.martinez@example.com',
    telefono: '3815550102',
    legajo: '1002',
    plan: 'Licenciatura en Administración',
    anoIngreso: 2021,
    fechaIngreso: new Date('2021-03-01'),
    estadoInscripcion: 'Regular',
    paisOrigen: 'Argentina',
  },
  {
    apellidoNombre: 'López Fernández, Carlos',
    tipoDocumento: 'DNI' as const,
    numeroDocumento: '37000345',
    fechaNacimiento: new Date('2000-11-05'),
    email: 'carlos.lopez@example.com',
    telefono: '3815550103',
    legajo: '1003',
    plan: 'Contador Público',
    anoIngreso: 2022,
    fechaIngreso: new Date('2022-03-01'),
    estadoInscripcion: 'Regular',
    paisOrigen: 'Argentina',
  },
  {
    apellidoNombre: 'González Pereyra, Ana',
    tipoDocumento: 'DNI' as const,
    numeroDocumento: '34000456',
    fechaNacimiento: new Date('1997-01-30'),
    email: 'ana.gonzalez@example.com',
    telefono: '3815550104',
    legajo: '1004',
    plan: 'Licenciatura en Economía',
    anoIngreso: 2019,
    fechaIngreso: new Date('2019-03-01'),
    estadoInscripcion: 'Egresado',
    paisOrigen: 'Argentina',
  },
  {
    apellidoNombre: 'Rodríguez Castro, Pedro',
    tipoDocumento: 'DNI' as const,
    numeroDocumento: '38000567',
    fechaNacimiento: new Date('2001-09-18'),
    email: 'pedro.rodriguez@example.com',
    telefono: '3815550105',
    legajo: '1005',
    plan: 'Contador Público',
    anoIngreso: 2023,
    fechaIngreso: new Date('2023-03-01'),
    estadoInscripcion: 'Regular',
    paisOrigen: 'Argentina',
  },
  {
    apellidoNombre: 'Fernández Díaz, Laura',
    tipoDocumento: 'LE' as const,
    numeroDocumento: 'LE123456',
    fechaNacimiento: new Date('1996-05-12'),
    email: 'laura.fernandez@example.com',
    telefono: '3815550106',
    legajo: '1006',
    plan: 'Licenciatura en Administración',
    anoIngreso: 2018,
    fechaIngreso: new Date('2018-03-01'),
    estadoInscripcion: 'Egresado',
    paisOrigen: 'Argentina',
  },
  {
    apellidoNombre: 'Díaz Molina, Roberto',
    tipoDocumento: 'DNI' as const,
    numeroDocumento: '39000678',
    fechaNacimiento: new Date('2002-12-25'),
    email: 'roberto.diaz@example.com',
    telefono: '3815550107',
    legajo: null,
    plan: 'Licenciatura en Economía',
    anoIngreso: 2024,
    fechaIngreso: new Date('2024-03-01'),
    estadoInscripcion: 'Regular',
    paisOrigen: 'Perú',
  },
  {
    apellidoNombre: 'Pereyra Sosa, Sofía',
    tipoDocumento: 'PASAPORTE' as const,
    numeroDocumento: 'AA123456',
    fechaNacimiento: new Date('1999-04-08'),
    email: 'sofia.pereyra@example.com',
    telefono: '3815550108',
    legajo: '1008',
    plan: 'Contador Público',
    anoIngreso: 2021,
    fechaIngreso: new Date('2021-03-01'),
    estadoInscripcion: 'Regular',
    paisOrigen: 'Bolivia',
  },
  {
    apellidoNombre: 'Castillo Vargas, Diego',
    tipoDocumento: 'DNI' as const,
    numeroDocumento: '41000789',
    fechaNacimiento: new Date('2000-08-14'),
    email: null,
    telefono: '3815550109',
    legajo: '1009',
    plan: 'Licenciatura en Administración',
    anoIngreso: 2022,
    fechaIngreso: new Date('2022-03-01'),
    estadoInscripcion: 'Regular',
    paisOrigen: 'Argentina',
  },
  {
    apellidoNombre: 'Molina Acosta, Florencia',
    tipoDocumento: 'LC' as const,
    numeroDocumento: 'LC987654',
    fechaNacimiento: new Date('1997-06-20'),
    email: 'florencia.molina@example.com',
    telefono: null,
    legajo: '1010',
    plan: 'Contador Público',
    anoIngreso: 2020,
    fechaIngreso: new Date('2020-03-01'),
    estadoInscripcion: 'Regular',
    paisOrigen: 'Argentina',
  },
]

const paises = [
  { idpais: 93, pais: 'Afganistán' },
  { idpais: 355, pais: 'Albania' },
  { idpais: 49, pais: 'Alemania' },
  { idpais: 376, pais: 'Andorra' },
  { idpais: 244, pais: 'Angola' },
  { idpais: 1268, pais: 'Antigua y Barbuda' },
  { idpais: 599, pais: 'Antillas Holandesas' },
  { idpais: 966, pais: 'Arabia Saudita' },
  { idpais: 213, pais: 'Argelia' },
  { idpais: 54, pais: 'Argentina' },
  { idpais: 374, pais: 'Armenia' },
  { idpais: 297, pais: 'Aruba' },
  { idpais: 61, pais: 'Australia' },
  { idpais: 43, pais: 'Austria' },
  { idpais: 994, pais: 'Azerbaiyán' },
  { idpais: 1242, pais: 'Bahamas' },
  { idpais: 973, pais: 'Bahrein' },
  { idpais: 880, pais: 'Bangladesh' },
  { idpais: 1246, pais: 'Barbados' },
  { idpais: 32, pais: 'Bélgica' },
  { idpais: 501, pais: 'Belice' },
  { idpais: 229, pais: 'Benin' },
  { idpais: 11, pais: 'Bermudas' },
  { idpais: 975, pais: 'Bhután' },
  { idpais: 375, pais: 'Bielorrusia' },
  { idpais: 591, pais: 'Bolivia' },
  { idpais: 387, pais: 'Bosnia y Herzegovina' },
  { idpais: 267, pais: 'Botswana' },
  { idpais: 55, pais: 'Brasil' },
  { idpais: 673, pais: 'Brunei' },
  { idpais: 359, pais: 'Bulgaria' },
  { idpais: 226, pais: 'Burkina Faso' },
  { idpais: 257, pais: 'Burundi' },
  { idpais: 238, pais: 'Cabo Verde' },
  { idpais: 855, pais: 'Camboya' },
  { idpais: 237, pais: 'Camerún' },
  { idpais: 2, pais: 'Canadá' },
  { idpais: 235, pais: 'Chad' },
  { idpais: 56, pais: 'Chile' },
  { idpais: 86, pais: 'China' },
  { idpais: 357, pais: 'Chipre' },
  { idpais: 379, pais: 'Ciudad del Vaticano' },
  { idpais: 57, pais: 'Colombia' },
  { idpais: 269, pais: 'Comoras' },
  { idpais: 242, pais: 'Congo' },
  { idpais: 850, pais: 'Corea del Norte' },
  { idpais: 82, pais: 'Corea del Sur' },
  { idpais: 225, pais: 'Costa de Marfil' },
  { idpais: 506, pais: 'Costa Rica' },
  { idpais: 385, pais: 'Croacia' },
  { idpais: 53, pais: 'Cuba' },
  { idpais: 45, pais: 'Dinamarca' },
  { idpais: 253, pais: 'Djibouti' },
  { idpais: 1767, pais: 'Dominica' },
  { idpais: 593, pais: 'Ecuador' },
  { idpais: 20, pais: 'Egipto' },
  { idpais: 503, pais: 'El Salvador' },
  { idpais: 971, pais: 'Emiratos Arabes Unidos' },
  { idpais: 291, pais: 'Eritrea' },
  { idpais: 421, pais: 'Eslovaquia' },
  { idpais: 386, pais: 'Eslovenia' },
  { idpais: 34, pais: 'España' },
  { idpais: 691, pais: 'Estados Federados de Micronesia' },
  { idpais: 1, pais: 'Estados Unidos' },
  { idpais: 372, pais: 'Estonia' },
  { idpais: 251, pais: 'Etiopía' },
  { idpais: 679, pais: 'Fidji' },
  { idpais: 63, pais: 'Filipinas' },
  { idpais: 358, pais: 'Finlandia' },
  { idpais: 33, pais: 'Francia' },
  { idpais: 241, pais: 'Gabón' },
  { idpais: 220, pais: 'Gambia' },
  { idpais: 995, pais: 'Georgia' },
  { idpais: 233, pais: 'Ghana' },
  { idpais: 1473, pais: 'Granada' },
  { idpais: 30, pais: 'Grecia' },
  { idpais: 502, pais: 'Guatemala' },
  { idpais: 594, pais: 'Guayana Francesa' },
  { idpais: 224, pais: 'Guinea' },
  { idpais: 245, pais: 'Guinea-Bissau' },
  { idpais: 240, pais: 'Guinea Ecuatorial' },
  { idpais: 592, pais: 'Guyana' },
  { idpais: 509, pais: 'Haití' },
  { idpais: 504, pais: 'Honduras' },
  { idpais: 852, pais: 'Hong Kong' },
  { idpais: 36, pais: 'Hungría' },
  { idpais: 91, pais: 'India' },
  { idpais: 62, pais: 'Indonesia' },
  { idpais: 964, pais: 'Irak' },
  { idpais: 98, pais: 'Irán' },
  { idpais: 353, pais: 'Irlanda' },
  { idpais: 354, pais: 'Islandia' },
  { idpais: 672, pais: 'Isla Norfolk' },
  { idpais: 692, pais: 'Islas Marshall' },
  { idpais: 677, pais: 'Islas Salomón' },
  { idpais: 972, pais: 'Israel' },
  { idpais: 39, pais: 'Italia' },
  { idpais: 5, pais: 'Jamaica' },
  { idpais: 81, pais: 'Japón' },
  { idpais: 962, pais: 'Jordania' },
  { idpais: 76, pais: 'Kazajstán' },
  { idpais: 254, pais: 'Kenia' },
  { idpais: 996, pais: 'Kirguistán' },
  { idpais: 686, pais: 'Kiribati' },
  { idpais: 965, pais: 'Kuwait' },
  { idpais: 856, pais: 'Laos' },
  { idpais: 266, pais: 'Lesotho' },
  { idpais: 371, pais: 'Letonia' },
  { idpais: 961, pais: 'Líbano' },
  { idpais: 231, pais: 'Liberia' },
  { idpais: 218, pais: 'Libia' },
  { idpais: 423, pais: 'Liechtenstein' },
  { idpais: 370, pais: 'Lituania' },
  { idpais: 352, pais: 'Luxemburgo' },
  { idpais: 853, pais: 'Macao' },
  { idpais: 389, pais: 'Macedonia' },
  { idpais: 261, pais: 'Madagascar' },
  { idpais: 60, pais: 'Malasia' },
  { idpais: 265, pais: 'Malawi' },
  { idpais: 960, pais: 'Maldivas' },
  { idpais: 223, pais: 'Malí' },
  { idpais: 356, pais: 'Malta' },
  { idpais: 212, pais: 'Marruecos' },
  { idpais: 596, pais: 'Martinica' },
  { idpais: 230, pais: 'Mauricio' },
  { idpais: 222, pais: 'Mauritania' },
  { idpais: 52, pais: 'México' },
  { idpais: 373, pais: 'Moldova' },
  { idpais: 377, pais: 'Mónaco' },
  { idpais: 976, pais: 'Mongolia' },
  { idpais: 382, pais: 'Montenegro' },
  { idpais: 258, pais: 'Mozambique' },
  { idpais: 95, pais: 'Myanmar (ex Birmania)' },
  { idpais: 264, pais: 'Namibia' },
  { idpais: 674, pais: 'Nauru' },
  { idpais: 977, pais: 'Nepal' },
  { idpais: 505, pais: 'Nicaragua' },
  { idpais: 227, pais: 'Níger' },
  { idpais: 234, pais: 'Nigeria' },
  { idpais: 47, pais: 'Noruega' },
  { idpais: 687, pais: 'Nueva Caledonia' },
  { idpais: 64, pais: 'Nueva Zelanda' },
  { idpais: 968, pais: 'Omán' },
  { idpais: 31, pais: 'Paises Bajos' },
  { idpais: 92, pais: 'Pakistán' },
  { idpais: 680, pais: 'Palau' },
  { idpais: 970, pais: 'Palestina' },
  { idpais: 507, pais: 'Panamá' },
  { idpais: 675, pais: 'Papua Nueva Guinea' },
  { idpais: 595, pais: 'Paraguay' },
  { idpais: 51, pais: 'Perú' },
  { idpais: 689, pais: 'Polinesia Francesa' },
  { idpais: 48, pais: 'Polonia' },
  { idpais: 351, pais: 'Portugal' },
  { idpais: 3, pais: 'Puerto Rico' },
  { idpais: 974, pais: 'Qatar' },
  { idpais: 44, pais: 'Reino Unido' },
  { idpais: 236, pais: 'República Centroafricana' },
  { idpais: 420, pais: 'República Checa' },
  { idpais: 243, pais: 'República Democrática del Congo' },
  { idpais: 4, pais: 'República Dominicana' },
  { idpais: 262, pais: 'Reunión' },
  { idpais: 250, pais: 'Ruanda' },
  { idpais: 40, pais: 'Rumania' },
  { idpais: 7, pais: 'Rusia' },
  { idpais: 685, pais: 'Samoa Occidental' },
  { idpais: 1869, pais: 'San Cristóbal y Nevis' },
  { idpais: 378, pais: 'San Marino' },
  { idpais: 290, pais: 'Santa Helena' },
  { idpais: 1758, pais: 'Santa Lucía' },
  { idpais: 239, pais: 'Santo Tomé y Príncipe' },
  { idpais: 1784, pais: 'San Vicente y Granadinas' },
  { idpais: 221, pais: 'Senegal' },
  { idpais: 381, pais: 'Serbia' },
  { idpais: 248, pais: 'Seychelles' },
  { idpais: 232, pais: 'Sierra Leona' },
  { idpais: 65, pais: 'Singapur' },
  { idpais: 963, pais: 'Siria' },
  { idpais: 252, pais: 'Somalia' },
  { idpais: 94, pais: 'Sri Lanka' },
  { idpais: 27, pais: 'Sudáfrica' },
  { idpais: 249, pais: 'Sudán' },
  { idpais: 283, pais: 'Sudán del Sur' },
  { idpais: 46, pais: 'Suecia' },
  { idpais: 41, pais: 'Suiza' },
  { idpais: 597, pais: 'Surinam' },
  { idpais: 268, pais: 'Swazilandia' },
  { idpais: 992, pais: 'Tadjikistán' },
  { idpais: 66, pais: 'Tailandia' },
  { idpais: 886, pais: 'Taiwan' },
  { idpais: 255, pais: 'Tanzania' },
  { idpais: 670, pais: 'Timor Oriental' },
  { idpais: 228, pais: 'Togo' },
  { idpais: 690, pais: 'Tokelau' },
  { idpais: 676, pais: 'Tonga' },
  { idpais: 868, pais: 'Trinidad y Tobago' },
  { idpais: 216, pais: 'Túnez' },
  { idpais: 993, pais: 'Turkmenistán' },
  { idpais: 90, pais: 'Turquía' },
  { idpais: 688, pais: 'Tuvalu' },
  { idpais: 380, pais: 'Ucrania' },
  { idpais: 256, pais: 'Uganda' },
  { idpais: 598, pais: 'Uruguay' },
  { idpais: 998, pais: 'Uzbekistán' },
  { idpais: 678, pais: 'Vanuatu' },
  { idpais: 58, pais: 'Venezuela' },
  { idpais: 84, pais: 'Vietnam' },
  { idpais: 967, pais: 'Yemen R.A.' },
  { idpais: 260, pais: 'Zambia' },
  { idpais: 263, pais: 'Zimbabwe' },
]

const pueblosOriginarios = [
  { idpueblooriginario: 0, pueblooriginario: 'Desconoce/No sabe' },
  { idpueblooriginario: 1, pueblooriginario: 'Atacama' },
  { idpueblooriginario: 2, pueblooriginario: 'Chané' },
  { idpueblooriginario: 3, pueblooriginario: 'Charrúa' },
  { idpueblooriginario: 4, pueblooriginario: 'Chicha' },
  { idpueblooriginario: 5, pueblooriginario: 'Chorote' },
  { idpueblooriginario: 6, pueblooriginario: 'Chulupí (Nivaclé)' },
  { idpueblooriginario: 7, pueblooriginario: 'Comechingón' },
  { idpueblooriginario: 8, pueblooriginario: 'Corundí' },
  { idpueblooriginario: 9, pueblooriginario: 'Diaguita' },
  { idpueblooriginario: 10, pueblooriginario: 'Fiscara' },
  { idpueblooriginario: 11, pueblooriginario: 'Guaraní' },
  { idpueblooriginario: 12, pueblooriginario: 'Guaycurú' },
  { idpueblooriginario: 13, pueblooriginario: 'Huarpe' },
  { idpueblooriginario: 14, pueblooriginario: 'Logys' },
  { idpueblooriginario: 15, pueblooriginario: 'Kolla' },
  { idpueblooriginario: 16, pueblooriginario: 'Kolla Atacameño' },
  { idpueblooriginario: 17, pueblooriginario: 'Lule' },
  { idpueblooriginario: 18, pueblooriginario: 'Lule Vilela' },
  { idpueblooriginario: 19, pueblooriginario: 'Mapuche' },
  { idpueblooriginario: 20, pueblooriginario: 'Mapuche Tehuelche' },
  { idpueblooriginario: 21, pueblooriginario: 'Mbya Guaraní' },
  { idpueblooriginario: 22, pueblooriginario: 'Moqoit (mocoví)' },
  { idpueblooriginario: 23, pueblooriginario: 'Ocloya' },
  { idpueblooriginario: 24, pueblooriginario: 'Omaguaca' },
  { idpueblooriginario: 25, pueblooriginario: 'Pilagá' },
  { idpueblooriginario: 26, pueblooriginario: 'Qom (Toba)' },
  { idpueblooriginario: 27, pueblooriginario: 'Quechua' },
  { idpueblooriginario: 28, pueblooriginario: 'Ranquel' },
  { idpueblooriginario: 29, pueblooriginario: 'Sanavirón' },
  { idpueblooriginario: 30, pueblooriginario: 'Selk´ Nam (Ona)' },
  { idpueblooriginario: 31, pueblooriginario: 'Tapiete' },
  { idpueblooriginario: 32, pueblooriginario: 'Tastil' },
  { idpueblooriginario: 33, pueblooriginario: 'Tehuelche' },
  { idpueblooriginario: 34, pueblooriginario: 'Tilián' },
  { idpueblooriginario: 35, pueblooriginario: 'Toara' },
  { idpueblooriginario: 36, pueblooriginario: 'Tonokoté' },
  { idpueblooriginario: 37, pueblooriginario: 'Vilela' },
  { idpueblooriginario: 38, pueblooriginario: 'Wichí' },
  { idpueblooriginario: 39, pueblooriginario: 'Yagan' },
  { idpueblooriginario: 40, pueblooriginario: 'Otro Especifique' },
]

async function main() {
  console.log('Insertando datos de ejemplo...')

  for (const a of alumnos) {
    await prisma.alumno.upsert({
      where: {
        tipoDocumento_numeroDocumento: {
          tipoDocumento: a.tipoDocumento,
          numeroDocumento: a.numeroDocumento,
        },
      },
      create: a,
      update: a,
    })
  }

  console.log(`${alumnos.length} alumnos insertados.`)

  console.log('Insertando países...')
  for (const p of paises) {
    await prisma.pais.upsert({
      where: { idpais: p.idpais },
      create: p,
      update: p,
    })
  }
  console.log(`${paises.length} países insertados.`)

  console.log('Insertando pueblos originarios...')
  for (const p of pueblosOriginarios) {
    await prisma.puebloOriginario.upsert({
      where: { idpueblooriginario: p.idpueblooriginario },
      create: p,
      update: p,
    })
  }
  console.log(`${pueblosOriginarios.length} pueblos originarios insertados.`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
